
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: kiddygeek-rails_development

test:
  <<: *default
  database: kiddygeek-rails_test

production:
  <<: *default
  database: kiddygeek-rails_production
  username: kiddygeek-rails
  password: <%= ENV['KIDDYGEEK-RAILS_DATABASE_PASSWORD'] %>
